### PR TITLE
add api: following() and dashboard()

### PR DESCRIPTION
**Pull request by zhanglongqi**
I just add two more api for convenient.

### CODE REVIEW

**Comment by michaelhelmick** [comment]
Hi, thanks for this, before I merge, can you just change the double quotes `"` to single quotes `'` to keep the code uniform.

As soon as that's done, I'll merge. Thanks!

**Comment by zhanglongqi** [comment]
Done

**Comment by michaelhelmick** [comment]
Thanks

**Comment by michaelhelmick** [comment]
`python-tumblpy 1.1.0` is available on pypi!

**Pull request merged**
