### PR TITLE
Fixed issue with oauth token decoding  

### PR DESCRIPTION
**Pull request by wmantly**

### CODE REVIEW

**Comment by michaelhelmick** [comment]
Hi, thanks for this. Does `request_tokens` with the current code return nothing after ran through `parse_qsl` and decoded? Is that the reason for moving it into the `authorized_tokens = ...` line?

**Comment by wmantly** [comment]
Yes, nothing, just by adding .decode to those 2 lines fixed the issue and i as able to use the wrapper fully after. I am not sure why this is needed now and wasn't before. 
Im sorry i did not provide more information, im still new at GIT.

**Comment by wmantly** [comment]
Here is my `pip3 freeze`

```
Django==1.7.2
dj-database-url==0.3.0
dj-static==0.0.6
django-redis-cache==0.13.0
django-toolbelt==0.0.1
gunicorn==19.1.1
oauthlib==0.7.2
psycopg2==2.5.4
py-oauth2==0.0.10
pyoauth2==0.0.4
redis==2.10.3
requests==2.5.1
requests-oauthlib==0.4.2
simplejson==3.6.5
static3==0.5.1
twython==3.2.0
```

**Comment by wmantly** [comment]
Please see new pull request.

**Comment by michaelhelmick** [comment]
This looks better. Can you please verify that it works in Python 2.7.x as well and I'll be happy to merge in :)

**Pull request closed without merging**
