### PR TITLE
Parsing blog URL

### LINKED ISSUE #39: request() fails if Tumblr returns https:// URL
I'm playing with a new Tumblr blog and using Tumblpy; it took me a bit to find out why it was failing. On my new blog, 

`the_client.post('user/info')['user']['blogs'][0]['url']`

returns a secure HTTP URL; lines 112 and 113 of `api.py` fail because they're explicitly matching for 'http://'.

Currently, I'm working around it by replacing 'https://' with 'http://' in a wrapper script, which seems to work fine.

### PR DESCRIPTION
**Pull request by bomb-on**
Fixes #39 and #45 - blog URL was not parsed properly if the blog is served over HTTPS.

### CODE REVIEW

**Comment by michaelhelmick** [comment]
Hey! Before merge yours, can you check this branch out and see if it works as well? #40 

https://github.com/michaelhelmick/python-tumblpy/tree/bugs-39

**Comment by bomb-on** [comment]
I can check it out later, although this is the same problem with a different solution... It seems a bit "dirty" to try to parse url with stripping first _n_ characters from the string, so I decided to use Python's `urlparse` module to get a proper blog name... My solution should support both `http` and `https` schemas, along with hard-coding the blog name without any schema (e.g. `myblog.tumblr.com`).

**Comment by michaelhelmick** [comment]
Touché. Good input!

**Comment by michaelhelmick** [comment]
Version 1.1.1 is available on pypi

**Comment by bomb-on** [comment]
Great! Thanks a bunch! ;)

**Pull request merged**
